
public class Job {
	protected Condition[] conditions;
	protected Job nextJob;
	
	public Job() {
		
	}
	

	
}


/*
ADD SHIP:
	JOBS:
		MOVE_JOB
			TO: 	LOC_1				
			COND: 	LOC_1 = this ship			LOC_RESERVATION_COND
			COND: 	FREE_WAY					FREE_WAY_COND
		MOVE JOB
			TO:		LOC_2
			COND: 	LOC_2 = this Ship			LOC_RESERVATION_COND
			COND: 	FREE_WAY					FREE_WAY_COND
		MOVE_JOB
			TO:		LOC_3
			COND: 	LOC_3 = this ship			LOC_RESERVATION_COND
			COND: 	FREE_WAY					FREE_WAY_COND
		LOSS_JOB
			TFE		INDEX_3
			COND: 	SHIP @ LOC_3				POSITION_COND
			COND: 	SHIP_STATUS = WAITING		SHIP_STATUS_COND
		LOSS_JOB
			TFE		INDEX_4
			COND:	SHIP @ LOC_3				POSITION_COND
			COND:	SHIP_STATUS = WAITING		SHIP_STATUS_COND
			COND:	NO_CRANES_OVER_SHIP			NO_CRANES_COND
			COND:	INDEX_3 = <EMPTY>			TFE_REMOVED_COND
		MOVE_JOB
			TO		LOC_4
			COND:	LOC_4 = this ship			LOC_RESERVATION_COND
			COND:	INDEX_4 = <EMPTY>			TFE_REMOVED_COND
			COND:	NO_CRANES_OVER_SHIP			NO_CRANES_COND
			COND:	FREE_WAY					FREE_WAY_COND
*/